// <auto-generated />
using System;
using AspnetCoreMvcFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspnetCoreMvcFull.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612023351_Audit")]
    partial class Audit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspnetCoreMvcFull.Models.AuditInstance", b =>
                {
                    b.Property<int>("AuditInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditInstanceId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("int");

                    b.Property<double>("PercentageScore")
                        .HasColumnType("float");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalMaxScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("AuditInstanceId");

                    b.HasIndex("FormTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("AuditInstances");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.AuditResponse", b =>
                {
                    b.Property<int>("AuditResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditResponseId"));

                    b.Property<int>("AuditInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("FormItemId")
                        .HasColumnType("int");

                    b.Property<string>("FormItemQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoopIndex")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPossibleScore")
                        .HasColumnType("int");

                    b.Property<int>("ScoredValue")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditResponseId");

                    b.HasIndex("AuditInstanceId");

                    b.HasIndex("FormItemId");

                    b.ToTable("AuditResponses");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ComplianceCategories");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceCategoryId");

                    b.HasIndex("TenantId");

                    b.ToTable("ComplianceFolders");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceFolderId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequiredDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceFolderId");

                    b.HasIndex("RequiredDocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.FormItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("HasLooping")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int?>("LoopCount")
                        .HasColumnType("int");

                    b.Property<string>("LoopLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("SectionId");

                    b.ToTable("FormItems");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.FormSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SectionId");

                    b.HasIndex("FormTypeId");

                    b.ToTable("FormSections");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.JenisForm", b =>
                {
                    b.Property<int>("FormTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormTypeId"));

                    b.Property<int?>("ComplianceCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("FormTypeId");

                    b.HasIndex("ComplianceCategoryId");

                    b.ToTable("JenisForms");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.RequiredDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceFolderId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceFolderId");

                    b.ToTable("RequiredDocuments");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.AuditInstance", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.JenisForm", "JenisForm")
                        .WithMany()
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JenisForm");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.AuditResponse", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.AuditInstance", "AuditInstance")
                        .WithMany("AuditResponses")
                        .HasForeignKey("AuditInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.FormItem", "FormItem")
                        .WithMany()
                        .HasForeignKey("FormItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditInstance");

                    b.Navigation("FormItem");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceCategory", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceFolder", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceCategory", "ComplianceCategory")
                        .WithMany("ComplianceFolders")
                        .HasForeignKey("ComplianceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceCategory");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Document", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceFolder", "ComplianceFolder")
                        .WithMany("Documents")
                        .HasForeignKey("ComplianceFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.RequiredDocument", "RequiredDocument")
                        .WithMany("Documents")
                        .HasForeignKey("RequiredDocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ComplianceFolder");

                    b.Navigation("RequiredDocument");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.FormItem", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.FormSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.FormSection", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.JenisForm", "JenisForm")
                        .WithMany("Sections")
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JenisForm");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.JenisForm", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceCategory", "ComplianceCategory")
                        .WithMany()
                        .HasForeignKey("ComplianceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ComplianceCategory");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.RequiredDocument", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceFolder", "ComplianceFolder")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("ComplianceFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceFolder");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.AuditInstance", b =>
                {
                    b.Navigation("AuditResponses");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceCategory", b =>
                {
                    b.Navigation("ComplianceFolders");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceFolder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("RequiredDocuments");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.FormSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.JenisForm", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.RequiredDocument", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
