// <auto-generated />
using System;
using AspnetCoreMvcFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspnetCoreMvcFull.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ComplianceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SOX",
                            Description = "Regulations for financial reporting.",
                            Name = "SOX (Sarbanes-Oxley)"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ISO",
                            Description = "Information security management system standard.",
                            Name = "ISO 27001"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GDPR",
                            Description = "General Data Protection Regulation.",
                            Name = "GDPR"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FINAUD",
                            Description = "Internal or external financial review.",
                            Name = "Financial Audit"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SECCOMP",
                            Description = "Adherence to security policies and standards.",
                            Name = "Security Compliance"
                        },
                        new
                        {
                            Id = 6,
                            Code = "QUALMAN",
                            Description = "Ensuring consistent quality of products/services.",
                            Name = "Quality Management"
                        },
                        new
                        {
                            Id = 7,
                            Code = "RISKMAN",
                            Description = "Identifying and mitigating potential risks.",
                            Name = "Risk Management"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CUST",
                            Description = "User-defined compliance type.",
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceCategoryId");

                    b.ToTable("ComplianceFolders");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceFolderId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequiredDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceFolderId");

                    b.HasIndex("RequiredDocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.RequiredDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceFolderId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceFolderId");

                    b.ToTable("RequiredDocuments");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceFolder", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceCategory", "ComplianceCategory")
                        .WithMany("ComplianceFolders")
                        .HasForeignKey("ComplianceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceCategory");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Document", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceFolder", "ComplianceFolder")
                        .WithMany("Documents")
                        .HasForeignKey("ComplianceFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.RequiredDocument", "RequiredDocument")
                        .WithMany("Documents")
                        .HasForeignKey("RequiredDocumentId");

                    b.Navigation("ComplianceFolder");

                    b.Navigation("RequiredDocument");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.RequiredDocument", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.ComplianceFolder", "ComplianceFolder")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("ComplianceFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceFolder");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceCategory", b =>
                {
                    b.Navigation("ComplianceFolders");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ComplianceFolder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("RequiredDocuments");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.RequiredDocument", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
